options:
  nova-compute-filesystem:
    type: string
    default:
    description: |
      The filesystem to mount when connected to nova-compute.
  nova-compute-mountpoint:
    type: string
    default: "/srv/nova"
    description: |
        The path to mount the filesystem at for nova-compute relations.
        If the path does not exist, it will be created.
  nova-compute-fstype:
    type: string
    default: nfs4
    description: "The filesystem type to be mounted. (ex: nfs4)"
  nova-compute-fsoptions:
    type: string
    default: 
    description: "Mount options."
  glance-filesystem:
    type: string
    default:
    description: |
      The filesystem to mount when connected to glance.
  glance-mountpoint:
    type: string
    default: "/srv/glance"
    description: |
        The path to mount the filesystem at for glance relations.  If the path
        does not exist, it will be created.
  glance-fstype:
    type: string
    default: nfs4
    description: "The filesystem type to be mounted. (ex: nfs4)"
  glance-fsoptions:
    type: string
    default: 
    description: "Mount options."
