options:
  filesystem:
    type: string
    default: 
    description: "The file system to mount. (ex: 192.168.1.1:/srv/data or /dev/sdb4)"
  mountpoint:
    type: string
    default: "/srv/nfsmount"
    description: |
        The path to mount the filesystem at.  If the path does not exist, it
        will be created.
  nova-directory:
    type: string
    default: nova
    description: |
        The path that will be configured in /etc/nova/nova.conf. Value is relative
        to the mountpoint.  If unspecified, the instances path will be set
        to <mountpoint>/nova.
  glance-directory:
    type: string
    default: glance
    description: |
        The path that will be configured in /etc/glance/glance-api.conf. Value is
        relative to the mountpoint.  If unspecified, the instances path will be set
        to <mountpoint>/glance.
  type:
    type: string
    default: nfs4
    description: "The filesystem type to be mounted. (ex: nfs4)"
  options:
    type: string
    default: 
    description: "Mount options."

